### PR TITLE
On branch edburns-msft-ibm-382-apply-lessons

### PR DESCRIPTION
**Pull request by edburns**
modified:   docs/howto-update-offer-in-partner-center.md

### CODE REVIEW

**Comment by majguo** [comment]
Commit [14058d8](https://github.com/WASdev/azure.liberty.aro/pull/97/commits/14058d802bacba0099e3d4c7e7e8961a0cc1330e) is to fix the most recent deployment issue reported by @edburns and @venunathb. The root cause is that when the new version `1.2.1` of OLO is available, the `startingCSV` doesn't work with `open-liberty-operator.v1.2.0` anymore. Updating to `open-liberty-operator.v1.2.1` solves the issue.

## Testing 

Manually install the OLO 1.2.1 to verify if the change works:
```
oc apply -f open-liberty-operator-subscription.yaml
# subscription.operators.coreos.com/open-liberty-certified created

oc get deployment -n openshift-operators -w
#NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
#olo-controller-manager   0/1     1            0           16s
#olo-controller-manager   1/1     1            1           30s
```

The OLO 1.2.1 is successfully installed:
image

**Review by edburns — COMMENTED** [review]
@majguo  I am very pleased with myself! I thought that was going to be the fix anyway!

**Comment by edburns** [comment]
Hello @venunathb , this workflow succeeded. https://github.com/azure-javaee/azure.liberty.aro/actions/runs/5497592098 . I request you to please merge this PR.

**Comment by venunathb** [comment]
@edburns @majguo 
Minor comment, I thought the OLO version would be updated via automation.
image

**Review by venunathb — APPROVED** [review]

**Pull request merged**
